### ISSUE TITLE
476 mb zip created for lambda deployment

### ISSUE THREAD

**Issue by ishita1995** [alecrubin/pytorch-serverless#2]
Hi,
Hope you are doing great. I have been using trying to deploy a pytorch model using serverless , I am facing problem regarding space . When using ssl deploy -v , the zip created in of size 476 mb and hence I am not able to deploy it on lambda.

I am pretty new to  this, so I am not able to figure out what exactly am I doing wrong.
![screenshot from 2018-06-15 17 12 53](https://user-images.githubusercontent.com/10631856/41466515-3dcad818-70c0-11e8-910d-c30ca1294d6c.png)

**Comment by alecrubin** [comment]
Hi! I’m going to need a bit more info to help, can you show me what your `serverless.yml` looks like?

**Comment by ishita1995** [comment]
![screenshot from 2018-06-18 14 48 12](https://user-images.githubusercontent.com/10631856/41528076-aa095778-7306-11e8-93f9-f6396fd62a54.png)
![screenshot from 2018-06-18 14 47 06](https://user-images.githubusercontent.com/10631856/41528008-84cc8106-7306-11e8-9d72-ca581dd9b2a5.png)

The serverless.yaml

**Comment by alecrubin** [comment]
Do you have any plugins defined in your serverless.yml? Usually it’s at the bottom.

**Comment by ishita1995** [comment]
yes I am using the python plugin

**Comment by alecrubin** [comment]
Make sure you have the serverless-python-requirements plugin installed. 
```sls plugin install -n serverless-python-requirements```

You’re going to want to make sure you installed the and your plugins confi should look like this ```plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
```

Also, make sure you exclude unnecessary files from deployment package
```package:
  exclude:
    - package.json
    - package-lock.json
    - README.md
    - node_modules/**
    - tests/**
    - .DS_Store
    - .idea/**```

**Comment by alecrubin** [comment]
Make sure you have the serverless-python-requirements plugin installed 
```
sls plugin install -n serverless-python-requirements
```

The plugins config in your `serverless.yml` should look like this 
```
plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
```

Also, make sure you exclude unnecessary files from your deployment package
```
package:
  exclude:
    - package.json
    - package-lock.json
    - README.md
    - node_modules/**
    - tests/**
    - .DS_Store
    - .idea/**
```
